name: Fetch Weather Data

on:
  schedule:
    # Runs every day at 04:00 UTC
    - cron:  '0 4 * * *'
  workflow_dispatch:   # allows manual trigger from GitHub UI

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch weather data
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          CITY: "London"         # change to your city if desired
        run: |
          python fetch_weather.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.json
          # Only commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "Update weather data [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
